### PR TITLE
Allow the parakeet to store it's data on a mongodb

### PR DESCRIPTION
**Pull request by tzachi-dar**

### CODE REVIEW

**Comment by jamorham** [comment]
Thanks for this contribution. I have an initial question about it.

What is the reason for storing this data in a remote mongo database? When would it be used?

**Comment by tzachi-dar** [comment]
Well, I store all my data from all receivers on mongodb, so it is nice to have the parakeet data there.

xDrip is running on a tablet, that one day will not work, and this is one more reason to store the data on a remote cloud. (I believe that lives of cellphones are even shorter...)

This is especially true since the google app engine does not store data for more than an hour.
So, if I wanted to go to sleep and see how long the parakeet battery will hold, I couldn't do it since, once I wake in the morning the data is not there (xDrip will keep reading the data from other receivers).

For this reasons, I have created the PR that allows the data to be stored also on the cloud.

**Comment by jamorham** [comment]
I think from what you are saying that this feature is for debugging/development purposes rather than general use as xDrip can already store the complete data including the calculated values in mongo or nightscout for long term storage. Is that right?

**Comment by tzachi-dar** [comment]
This is indeed mainly for development and debug.
Xdrip does not store this data since it removes duplicate packets, and
therefor some data might be lost
For example battery or exact time of packet captured ( if therefor is more
then receiver).

בתאריך 18 באוג׳ 2016 3:32 אחה״צ,‏ "Jamorham" notifications@github.com כתב:

**Comment by jamorham** [comment]
Okay so regarding the implementation, I think the placement of the call to the `send_to_mongo` function should be moved. 

Where it currently is inside `save_record_to_memcache` could cause problems especially if the `send_to_mongo` function takes a long time to return as the memcache would not be updated when xdrip is trying to read it.

I suggest moving the call instead to where new data arrives in the section for `receiver.cgi`  after this line: https://github.com/tzachi-dar/Parakeet-App-Engine/blob/da23457bed5a7f94a2dd3182c4ea2aca7b205c38/main.py#L348

Considering the same edge cases (mlab being down etc) Does a timeout need to be specified with the calls to `urllib` to avoid lockups or free-tier cpu cost related issues?

I think the informative text should be updated to indicate that the feature is for development/debugging and that it works with mlab.com specifically and unless you are a developer there is no need to consider setting those parameters.

There also appears to be some unrelated code added for a `ti` parameter for `TransmissionId` which I don't think is supported by the parakeet or consolidated usb wixel python script.

**Comment by tzachi-dar** [comment]
Ok, looked at all logs, and it seems that the write operation takes by average 400 ms.
So, I give it a timeout of 4 seconds, to allow requests to complete, but not block other server operation in the case of error.
Also changed logging and moved the function send_to_mongo to your proposed location.

**Comment by jamorham** [comment]
Okay this looks good I think. Can you confirm that you have tested it successfully both with and without the Key set and using the published Parakeet firmware? 

Reading through the changes I can't see any obvious problems as everything should be conditional but I don't plan to test it myself until after merging so please let me know that you have tested things successfully at your end.

Thanks.

**Comment by tzachi-dar** [comment]
Tested most of the casses that you have asked for.
Will test some more and let you know when all scenarios pass.

Tzachi

**Comment by tzachi-dar** [comment]
OK, tested all casses and it seems to work well.

**Comment by jamorham** [comment]
Merged, thanks!

**Pull request merged**
